export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_CODE = {
  VALIDATION: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND_ERROR",
  INTERNAL: "INTERNAL_ERROR",
} as const;
